### ISSUE TITLE
Add custom rule edition for security groups using an $EDITOR

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1006]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Security groups can have many custom rules that can be cumbersome to edit and write one by one. Do so in the CLI could potentially take a long time to develop. It would be more effective to have an interactive way to edit them based on an editor such as `git rebase -i`.  By doing so, we can leverage the knowledge of our users with their favorite text editor.

The text would look like this:

```yaml
enable_smtp: true
# Inbound rules are applied to the network flux coming IN of your instance
inbound_rules:
  - {rule: deny,   protocol: tcp, port: 42, ip_range: 0.0.0.0/0}
# Outbound rules are applied to the network flux coming OUT of your instance
outbound_rules:
  - {rule: accept, protocol: tcp, port: 42, ip_range: 0.0.0.0/0}
```

### How I imagine scw could expose this functionality

`scw instance security-group edit`

### References

- `git rebase -i`
- https://github.com/AlecAivazis/survey
- kubectl edit
